FROM nginx:1.15.0-alpine


RUN rm /etc/nginx/conf.d/default.conf
# COPY html /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d
RUN mkdir /var/www/html -p && touch /var/www/html/index.php

EXPOSE 80