version: '3'

services:

  laravel:
    image: jatabara/laravel:prod
    container_name: laravel
    networks:
      - laranet
  nginx:
    image: jatabara/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "6060:80"
networks:
  laranet:
    driver: brigde